name: CI/CD Pipeline
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
      - name: Build Docker image
        run: |
          cd server
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/task-tracker:latest .

      - name: Push to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/task-tracker:latest

      - name: Install IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh

      - name: Login to IBM Cloud
        run: |
          ibmcloud login --apikey ${{ secrets.IBM_CLOUD_API_KEY }}
          ibmcloud target -g Default -r us-south

      - name: Deploy to Code Engine
        run: |
          ibmcloud ce project target -n task-tracker-project || ibmcloud ce project create -n task-tracker-project
          ibmcloud ce application create \
            --name task-tracker-app \
            --image ${{ secrets.DOCKERHUB_USERNAME }}/task-tracker:latest \
            --port 8080 \
            --env PORT=8080 \
            --memory 512M \
            --cpu 1