name: CI/CD Pipeline
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          cd server
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/task-tracker:latest .

      - name: Push to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        env:
          IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/task-tracker:latest
        run: |
          docker push $IMAGE

      - name: Deploy to IBM Cloud Code Engine
        uses: ibm-actions/github-action-ibm-cloud-login@v1
        with:
          ibmcloud_api_key: ${{ secrets.IBM_CLOUD_API_KEY }}

      - name: Deploy app to Code Engine
        run: |
          ibmcloud target -g Default -r us-south
          ibmcloud ce project target -n task-tracker-project || ibmcloud ce project create -n task-tracker-project
          ibmcloud ce application create \
            --name task-tracker-app \
            --image ${{ secrets.DOCKERHUB_USERNAME }}/task-tracker:latest \
            --port 8080 \
            --env PORT=8080 \
            --memory 512M \
            --cpu 1
